/// <reference types="node" />
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient, InterventionStatus, PaymentMethod } from '@prisma/client';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

function makeDate(monthOffset: number, day: number, hour = 9, minute = 0) {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth() + monthOffset, day, hour, minute, 0, 0);
}

async function main() {
  await prisma.intervention.deleteMany();
  await prisma.client.deleteMany();

  await prisma.userSetting.upsert({
    where: { id: 1 },
    update: {
      activityName: 'Christophe Électricité',
      monthlyLimit: 3500,
      currency: 'EUR',
    },
    create: {
      id: 1,
      activityName: 'Christophe Électricité',
      monthlyLimit: 3500,
      currency: 'EUR',
    },
  });

  const clients = await Promise.all([
    prisma.client.create({
      data: {
        firstName: 'Jean',
        lastName: 'Dupont',
        phone: '0470 00 00 00',
        email: 'jean.dupont@example.com',
        address: 'Rue des Artisans 12',
        postalCode: '4000',
        city: 'Liège',
        notes: 'Maison ancienne, installation parfois capricieuse.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Sophie',
        lastName: 'Martin',
        phone: '0471 11 22 33',
        email: 'sophie.martin@example.com',
        address: 'Avenue des Tilleuls 8',
        postalCode: '4100',
        city: 'Seraing',
        notes: 'Souhaite des rendez-vous tôt le matin.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Karim',
        lastName: 'Bensaid',
        phone: '0485 22 33 44',
        email: 'karim.bensaid@example.com',
        address: 'Rue du Centre 5',
        postalCode: '4020',
        city: 'Liège',
        notes: 'Petit commerce, coupures à éviter en journée.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Claire',
        lastName: 'Lambert',
        phone: '0492 10 20 30',
        email: 'claire.lambert@example.com',
        address: 'Chemin du Bois 19',
        postalCode: '4050',
        city: 'Chaudfontaine',
        notes: 'Projet de rénovation complet par étapes.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Marc',
        lastName: 'Leroy',
        phone: '0495 45 67 89',
        email: 'marc.leroy@example.com',
        address: 'Rue du Stade 3',
        postalCode: '4430',
        city: 'Ans',
        notes: 'Interventions rapides entre midi et deux.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Julie',
        lastName: 'Masson',
        phone: '0478 55 44 33',
        email: 'julie.masson@example.com',
        address: 'Clos du Verger 27',
        postalCode: '4340',
        city: 'Awans',
        notes: 'Veut tout suivre par email avec devis clairs.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Nathalie',
        lastName: 'Bernard',
        phone: '0486 12 34 56',
        email: 'nathalie.bernard@example.com',
        address: 'Rue des Mésanges 14',
        postalCode: '4030',
        city: 'Grivegnée',
        notes: 'Particulier, aime planifier plusieurs petits travaux groupés.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Olivier',
        lastName: 'Vandevelde',
        phone: '0487 66 77 88',
        email: 'olivier.vandevelde@example.com',
        address: 'Boulevard Pasteur 44',
        postalCode: '4102',
        city: 'Ougrée',
        notes: 'Syndic d’immeuble, interventions souvent urgentes dans les communs.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Emma',
        lastName: 'Rossi',
        phone: '0477 98 76 54',
        email: 'emma.rossi@example.com',
        address: 'Rue des Carmes 2',
        postalCode: '4000',
        city: 'Liège',
        notes: 'Cabinet paramédical, créneaux possibles uniquement après 18h.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Luc',
        lastName: 'Goffin',
        phone: '0491 23 98 45',
        email: 'luc.goffin@example.com',
        address: 'Rue Haute 61',
        postalCode: '4460',
        city: 'Grâce-Hollogne',
        notes: 'Atelier mécanique, besoin fréquent de dépannages rapides.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Anne',
        lastName: 'Dubois',
        phone: '0493 88 77 66',
        email: 'anne.dubois@example.com',
        address: 'Rue de la Fontaine 31',
        postalCode: '4120',
        city: 'Neupré',
        notes: 'Maison en rénovation, paiements échelonnés.',
      },
    }),
    prisma.client.create({
      data: {
        firstName: 'Pierre',
        lastName: 'Renard',
        phone: '0484 55 66 11',
        email: 'pierre.renard@example.com',
        address: 'Allée des Chênes 7',
        postalCode: '4140',
        city: 'Sprimont',
        notes: 'Petit commerce alimentaire, sensible aux coupures en journée.',
      },
    }),
  ]);

  const [jean, sophie, karim, claire, marc, julie, nathalie, olivier, emma, luc, anne, pierre] = clients;

  const interventions = [
    {
      clientId: jean.id,
      date: makeDate(0, 3, 8, 30),
      workType: 'Remplacement tableau électrique',
      description: 'Mise en conformité partielle et repérage des circuits.',
      estimatedDurationHours: 6,
      actualDurationHours: 6.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 780,
      receivedAmount: 780,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(0, 5, 14, 0),
      notes: 'Prévoir une seconde phase pour le garage.',
    },
    {
      clientId: sophie.id,
      date: makeDate(0, 8, 9, 0),
      workType: 'Ajout prises cuisine',
      description: 'Deux nouvelles prises au-dessus du plan de travail.',
      estimatedDurationHours: 2.5,
      actualDurationHours: 2,
      status: InterventionStatus.TERMINEE,
      plannedAmount: 240,
      receivedAmount: 120,
      paymentMethod: PaymentMethod.CARTE,
      notes: 'Reste à encaisser sur facture.',
    },
    {
      clientId: karim.id,
      date: makeDate(0, 10, 7, 30),
      workType: 'Dépannage éclairage boutique',
      description: 'Recherche de panne et remplacement alimentation LED.',
      estimatedDurationHours: 3,
      actualDurationHours: 2.5,
      status: InterventionStatus.FACTUREE,
      plannedAmount: 310,
      receivedAmount: 0,
      paymentMethod: PaymentMethod.VIREMENT,
      notes: 'Facture envoyée, attente du paiement.',
    },
    {
      clientId: claire.id,
      date: makeDate(0, 15, 8, 0),
      workType: 'Pré-câblage extension',
      description: 'Passage des gaines et positionnement des points lumineux.',
      estimatedDurationHours: 7,
      actualDurationHours: null,
      status: InterventionStatus.EN_COURS,
      plannedAmount: 950,
      receivedAmount: 300,
      paymentMethod: PaymentMethod.VIREMENT,
      notes: 'Deuxième journée à planifier avec le plafonneur.',
    },
    {
      clientId: marc.id,
      date: makeDate(0, 22, 13, 30),
      workType: 'Pose sonnette connectée',
      description: 'Installation et paramétrage application mobile.',
      estimatedDurationHours: 1.5,
      actualDurationHours: null,
      status: InterventionStatus.A_FAIRE,
      plannedAmount: 145,
      receivedAmount: 0,
      paymentMethod: PaymentMethod.CARTE,
      notes: 'Client déjà équipé du Wi-Fi à proximité.',
    },
    {
      clientId: julie.id,
      date: makeDate(-1, 7, 9, 0),
      workType: 'Remplacement spots salle de bain',
      description: 'Pose de spots IP44 et test différentiel.',
      estimatedDurationHours: 2,
      actualDurationHours: 2,
      status: InterventionStatus.PAYEE,
      plannedAmount: 220,
      receivedAmount: 220,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(-1, 7, 11, 30),
      notes: null,
    },
    {
      clientId: jean.id,
      date: makeDate(-1, 18, 8, 30),
      workType: 'Ajout ligne lave-linge',
      description: 'Création circuit dédié depuis le tableau principal.',
      estimatedDurationHours: 4,
      actualDurationHours: 4,
      status: InterventionStatus.PAYEE,
      plannedAmount: 360,
      receivedAmount: 360,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-1, 21, 10, 0),
      notes: null,
    },
    {
      clientId: claire.id,
      date: makeDate(-2, 4, 8, 0),
      workType: 'Visite technique rénovation',
      description: 'Relevé sur site et préparation d’un phasage de chantier.',
      estimatedDurationHours: 1.5,
      actualDurationHours: 1.5,
      status: InterventionStatus.FACTUREE,
      plannedAmount: 90,
      receivedAmount: 90,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-2, 6, 9, 0),
      notes: 'Convertie ensuite en chantier.',
    },
    {
      clientId: sophie.id,
      date: makeDate(-2, 12, 14, 0),
      workType: 'Mise en sécurité cave',
      description: 'Remplacement boîtes vétustes et isolation des connexions.',
      estimatedDurationHours: 3,
      actualDurationHours: 3.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 295,
      receivedAmount: 295,
      paymentMethod: PaymentMethod.ESPECES,
      paymentDate: makeDate(-2, 12, 17, 30),
      notes: null,
    },
    {
      clientId: karim.id,
      date: makeDate(-3, 2, 7, 0),
      workType: 'Maintenance éclairage vitrine',
      description: 'Contrôle général avant période de soldes.',
      estimatedDurationHours: 2,
      actualDurationHours: 2,
      status: InterventionStatus.TERMINEE,
      plannedAmount: 180,
      receivedAmount: 80,
      paymentMethod: PaymentMethod.VIREMENT,
      notes: 'Prévoir un remplacement complet l’hiver prochain.',
    },
    {
      clientId: marc.id,
      date: makeDate(-3, 20, 10, 0),
      workType: 'Remplacement coffret garage',
      description: 'Coffret modulaire 2 rangées avec repérage circuits.',
      estimatedDurationHours: 5,
      actualDurationHours: 5.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 640,
      receivedAmount: 640,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-3, 25, 9, 0),
      notes: null,
    },
    {
      clientId: julie.id,
      date: makeDate(-4, 9, 9, 30),
      workType: 'Création éclairage terrasse',
      description: 'Pose de bornes lumineuses et horloge crépusculaire.',
      estimatedDurationHours: 4,
      actualDurationHours: 4,
      status: InterventionStatus.PAYEE,
      plannedAmount: 520,
      receivedAmount: 520,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-4, 16, 12, 0),
      notes: null,
    },
    {
      clientId: jean.id,
      date: makeDate(-5, 14, 8, 0),
      workType: 'Déplacement prise atelier',
      description: 'Adaptation suivant nouvel aménagement des établis.',
      estimatedDurationHours: 2,
      actualDurationHours: 2,
      status: InterventionStatus.PAYEE,
      plannedAmount: 165,
      receivedAmount: 165,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(-5, 14, 11, 0),
      notes: null,
    },
    {
      clientId: claire.id,
      date: makeDate(-6, 5, 8, 30),
      workType: 'Installation bornier domotique',
      description: 'Préparation pour centralisation de volets et éclairages.',
      estimatedDurationHours: 6,
      actualDurationHours: 6,
      status: InterventionStatus.PAYEE,
      plannedAmount: 860,
      receivedAmount: 860,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-6, 10, 15, 0),
      notes: null,
    },
    {
      clientId: sophie.id,
      date: makeDate(-7, 17, 9, 0),
      workType: 'Diagnostic disjonctions répétées',
      description: 'Répartition des charges et remplacement d’un disjoncteur.',
      estimatedDurationHours: 2,
      actualDurationHours: 2.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 210,
      receivedAmount: 210,
      paymentMethod: PaymentMethod.ESPECES,
      paymentDate: makeDate(-7, 17, 12, 0),
      notes: null,
    },
    {
      clientId: karim.id,
      date: makeDate(-8, 11, 7, 30),
      workType: 'Pose éclairage réserve',
      description: 'Ajout de deux lignes LED et d’un interrupteur bipolaire.',
      estimatedDurationHours: 3,
      actualDurationHours: 3,
      status: InterventionStatus.PAYEE,
      plannedAmount: 275,
      receivedAmount: 275,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(-8, 11, 11, 0),
      notes: null,
    },
    {
      clientId: marc.id,
      date: makeDate(-9, 23, 10, 30),
      workType: 'Motorisation portail alimentation',
      description: 'Alimentation dédiée et protection adaptée.',
      estimatedDurationHours: 4,
      actualDurationHours: 4.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 430,
      receivedAmount: 430,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-9, 28, 9, 0),
      notes: null,
    },
    {
      clientId: julie.id,
      date: makeDate(-10, 6, 9, 0),
      workType: 'Sécurisation tableau cave',
      description: 'Ajout différentiel et étiquetage complet.',
      estimatedDurationHours: 3.5,
      actualDurationHours: 3.5,
      status: InterventionStatus.ANNULEE,
      plannedAmount: 300,
      receivedAmount: 0,
      paymentMethod: PaymentMethod.AUTRE,
      notes: 'Client a reporté le chantier sine die.',
    },
    {
      clientId: claire.id,
      date: makeDate(-11, 15, 8, 30),
      workType: 'Préparation devis rénovation cuisine',
      description: 'Repérage circuits, prises et électroménager.',
      estimatedDurationHours: 1,
      actualDurationHours: 1,
      status: InterventionStatus.PAYEE,
      plannedAmount: 75,
      receivedAmount: 75,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-11, 15, 10, 0),
      notes: null,
    },
    {
      clientId: nathalie.id,
      date: makeDate(0, 4, 13, 30),
      workType: 'Ajout prises bureau',
      description: 'Création de trois prises pour poste télétravail.',
      estimatedDurationHours: 2,
      actualDurationHours: 2,
      status: InterventionStatus.PAYEE,
      plannedAmount: 260,
      receivedAmount: 260,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(0, 4, 16, 0),
      notes: null,
    },
    {
      clientId: olivier.id,
      date: makeDate(0, 6, 8, 0),
      workType: 'Réparation éclairage communs',
      description: 'Remplacement détecteur et trois luminaires d’escalier.',
      estimatedDurationHours: 3,
      actualDurationHours: 3.5,
      status: InterventionStatus.FACTUREE,
      plannedAmount: 420,
      receivedAmount: 0,
      paymentMethod: PaymentMethod.VIREMENT,
      notes: 'Syndic paie généralement à 30 jours.',
    },
    {
      clientId: emma.id,
      date: makeDate(0, 11, 18, 30),
      workType: 'Création ligne climatisation',
      description: 'Circuit dédié et protection au tableau pour cabinet.',
      estimatedDurationHours: 4,
      actualDurationHours: 4,
      status: InterventionStatus.TERMINEE,
      plannedAmount: 560,
      receivedAmount: 300,
      paymentMethod: PaymentMethod.VIREMENT,
      notes: 'Solde à régler après réception du devis signé.',
    },
    {
      clientId: luc.id,
      date: makeDate(0, 13, 7, 0),
      workType: 'Dépannage pont élévateur',
      description: 'Contrôle de l’alimentation et remplacement disjoncteur moteur.',
      estimatedDurationHours: 2,
      actualDurationHours: 1.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 230,
      receivedAmount: 230,
      paymentMethod: PaymentMethod.ESPECES,
      paymentDate: makeDate(0, 13, 9, 30),
      notes: 'Client fidèle, intervention urgente.',
    },
    {
      clientId: anne.id,
      date: makeDate(0, 18, 8, 30),
      workType: 'Rénovation étage - phase 2',
      description: 'Câblage chambres et couloir, attente appareillage final.',
      estimatedDurationHours: 8,
      actualDurationHours: 7.5,
      status: InterventionStatus.EN_COURS,
      plannedAmount: 1250,
      receivedAmount: 500,
      paymentMethod: PaymentMethod.VIREMENT,
      notes: 'Chantier en trois acomptes.',
    },
    {
      clientId: pierre.id,
      date: makeDate(0, 24, 6, 30),
      workType: 'Contrôle vitrine réfrigérée',
      description: 'Vérification alimentation et remplacement prise industrielle.',
      estimatedDurationHours: 1.5,
      actualDurationHours: null,
      status: InterventionStatus.A_FAIRE,
      plannedAmount: 190,
      receivedAmount: 0,
      paymentMethod: PaymentMethod.VIREMENT,
      notes: 'À caler avant l’ouverture du magasin.',
    },
    {
      clientId: olivier.id,
      date: makeDate(-1, 3, 8, 0),
      workType: 'Mise aux normes cave immeuble',
      description: 'Sécurisation coffret et repérage des départs.',
      estimatedDurationHours: 5,
      actualDurationHours: 5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 690,
      receivedAmount: 690,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-1, 28, 10, 0),
      notes: null,
    },
    {
      clientId: emma.id,
      date: makeDate(-1, 9, 19, 0),
      workType: 'Éclairage salle d’attente',
      description: 'Passage en LED chaude avec gradation douce.',
      estimatedDurationHours: 2.5,
      actualDurationHours: 2.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 340,
      receivedAmount: 340,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(-1, 9, 21, 30),
      notes: null,
    },
    {
      clientId: luc.id,
      date: makeDate(-1, 16, 7, 30),
      workType: 'Ajout prise triphasée atelier',
      description: 'Alimentation nouvelle machine de découpe.',
      estimatedDurationHours: 4,
      actualDurationHours: 4,
      status: InterventionStatus.FACTUREE,
      plannedAmount: 480,
      receivedAmount: 180,
      paymentMethod: PaymentMethod.VIREMENT,
      notes: 'Reste dû, relance prévue en fin de mois.',
    },
    {
      clientId: anne.id,
      date: makeDate(-1, 20, 8, 30),
      workType: 'Dépose ancienne installation',
      description: 'Retrait appareillage vétuste et sécurisation provisoire.',
      estimatedDurationHours: 6,
      actualDurationHours: 6,
      status: InterventionStatus.PAYEE,
      plannedAmount: 720,
      receivedAmount: 720,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-1, 22, 15, 0),
      notes: null,
    },
    {
      clientId: pierre.id,
      date: makeDate(-1, 25, 6, 45),
      workType: 'Remplacement éclairage réserve',
      description: 'Pose de dalles LED plus économiques.',
      estimatedDurationHours: 2,
      actualDurationHours: 2,
      status: InterventionStatus.PAYEE,
      plannedAmount: 265,
      receivedAmount: 265,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(-1, 25, 9, 30),
      notes: null,
    },
    {
      clientId: nathalie.id,
      date: makeDate(-2, 6, 10, 0),
      workType: 'Pose luminaires séjour',
      description: 'Installation de deux suspensions et variateur.',
      estimatedDurationHours: 2,
      actualDurationHours: 2,
      status: InterventionStatus.PAYEE,
      plannedAmount: 180,
      receivedAmount: 180,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(-2, 6, 12, 30),
      notes: null,
    },
    {
      clientId: olivier.id,
      date: makeDate(-2, 10, 8, 30),
      workType: 'Interphone immeuble',
      description: 'Diagnostic alimentation et remplacement transformateur.',
      estimatedDurationHours: 3,
      actualDurationHours: 3,
      status: InterventionStatus.PAYEE,
      plannedAmount: 395,
      receivedAmount: 395,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-2, 30, 14, 0),
      notes: null,
    },
    {
      clientId: luc.id,
      date: makeDate(-2, 19, 7, 0),
      workType: 'Sécurisation compresseur',
      description: 'Ajout protection différentielle type A.',
      estimatedDurationHours: 2.5,
      actualDurationHours: 2,
      status: InterventionStatus.PAYEE,
      plannedAmount: 215,
      receivedAmount: 215,
      paymentMethod: PaymentMethod.ESPECES,
      paymentDate: makeDate(-2, 19, 9, 15),
      notes: null,
    },
    {
      clientId: pierre.id,
      date: makeDate(-3, 5, 6, 30),
      workType: 'Dépannage chambre froide',
      description: 'Recherche faux-contact sur alimentation ventilateurs.',
      estimatedDurationHours: 1.5,
      actualDurationHours: 1.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 175,
      receivedAmount: 175,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(-3, 5, 8, 45),
      notes: 'Intervention avant ouverture.',
    },
    {
      clientId: emma.id,
      date: makeDate(-3, 14, 19, 0),
      workType: 'Ajout alimentation salle de soins',
      description: 'Nouvelle ligne pour équipement esthétique.',
      estimatedDurationHours: 3.5,
      actualDurationHours: 3.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 455,
      receivedAmount: 455,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-3, 19, 12, 0),
      notes: null,
    },
    {
      clientId: anne.id,
      date: makeDate(-4, 11, 8, 0),
      workType: 'Rénovation étage - phase 1',
      description: 'Départ chantier avec préparation tableau secondaire.',
      estimatedDurationHours: 7,
      actualDurationHours: 7,
      status: InterventionStatus.PAYEE,
      plannedAmount: 980,
      receivedAmount: 980,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-4, 15, 16, 0),
      notes: 'Premier acompte encaissé.',
    },
    {
      clientId: nathalie.id,
      date: makeDate(-5, 4, 14, 0),
      workType: 'Remplacement extraction salle de bain',
      description: 'Pose d’un modèle temporisé et raccordement.',
      estimatedDurationHours: 1.5,
      actualDurationHours: 1.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 155,
      receivedAmount: 155,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(-5, 4, 16, 0),
      notes: null,
    },
    {
      clientId: olivier.id,
      date: makeDate(-6, 21, 8, 0),
      workType: 'Remplacement minuterie communs',
      description: 'Réglage et test sur trois étages.',
      estimatedDurationHours: 2,
      actualDurationHours: 2,
      status: InterventionStatus.PAYEE,
      plannedAmount: 240,
      receivedAmount: 240,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-6, 29, 10, 0),
      notes: null,
    },
    {
      clientId: emma.id,
      date: makeDate(-7, 8, 18, 30),
      workType: 'Contrôle différentiel cabinet',
      description: 'Test et remplacement d’un module défectueux.',
      estimatedDurationHours: 1,
      actualDurationHours: 1,
      status: InterventionStatus.PAYEE,
      plannedAmount: 95,
      receivedAmount: 95,
      paymentMethod: PaymentMethod.CARTE,
      paymentDate: makeDate(-7, 8, 19, 45),
      notes: null,
    },
    {
      clientId: luc.id,
      date: makeDate(-8, 22, 7, 0),
      workType: 'Ajout éclairage zone ponts',
      description: 'Pose de deux projecteurs LED en atelier.',
      estimatedDurationHours: 2.5,
      actualDurationHours: 2.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 285,
      receivedAmount: 285,
      paymentMethod: PaymentMethod.ESPECES,
      paymentDate: makeDate(-8, 22, 10, 30),
      notes: null,
    },
    {
      clientId: pierre.id,
      date: makeDate(-9, 12, 6, 30),
      workType: 'Prise secourue caisse',
      description: 'Ajout alimentation protégée sur ligne prioritaire.',
      estimatedDurationHours: 2,
      actualDurationHours: 2,
      status: InterventionStatus.PAYEE,
      plannedAmount: 225,
      receivedAmount: 225,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-9, 18, 9, 0),
      notes: null,
    },
    {
      clientId: anne.id,
      date: makeDate(-10, 18, 8, 30),
      workType: 'Devis rénovation complète',
      description: 'Visite détaillée, prise de mesures et budget par phases.',
      estimatedDurationHours: 1.5,
      actualDurationHours: 1.5,
      status: InterventionStatus.PAYEE,
      plannedAmount: 110,
      receivedAmount: 110,
      paymentMethod: PaymentMethod.VIREMENT,
      paymentDate: makeDate(-10, 18, 11, 0),
      notes: 'Client transformé ensuite en chantier.',
    },
  ];

  for (const intervention of interventions) {
    await prisma.intervention.create({ data: intervention });
  }

  console.log(`✓ Seed terminé : ${clients.length} clients, ${interventions.length} interventions`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
